import type { ShopUpgrade, Customer, LoreEntry } from './types';

export const UPGRADES: ShopUpgrade[] = [
  {
    id: 'glowing_ink',
    name: 'Glowing Ink',
    description: '+10% accuracy on all maps. The ink remembers what the hand forgets.',
    icon: '✨',
    cost: 60,
    purchased: false,
    effect: 'accuracy_bonus',
  },
  {
    id: 'sturdy_desk',
    name: 'Reinforced Desk',
    description: 'Angry clients do less damage to your reputation (-8 instead of -15). A stout desk inspires stout confidence.',
    icon: '🪵',
    cost: 50,
    purchased: false,
    effect: 'reputation_shield',
  },
  {
    id: 'magnifying_glass',
    name: 'Crystal Monocle',
    description: 'Customers offer one extra clue hint. The crystal reveals what polite silence obscures.',
    icon: '🔮',
    cost: 80,
    purchased: false,
    effect: 'extra_clue',
  },
  {
    id: 'enchanted_parchment',
    name: 'Enchanted Parchment',
    description: 'Earn 20% more gold per completed map. Premium materials command premium prices.',
    icon: '📜',
    cost: 70,
    purchased: false,
    effect: 'gold_bonus',
  },
  {
    id: 'cozy_decor',
    name: 'Cozy Decor',
    description: 'Monster clients feel at home and pay 30% more. Nothing says hospitality like a skull-shaped candleholder.',
    icon: '🕯️',
    cost: 90,
    purchased: false,
    effect: 'cozy_decor',
  },
  {
    id: 'enchanted_ink',
    name: 'Enchanted Ink',
    description: 'Two random correct tiles are revealed at the start of each map. The ink knows more than you do.',
    icon: '🔊',
    cost: 120,
    purchased: false,
    effect: 'enchanted_ink',
  },
];

export const CUSTOMERS: Customer[] = [
  // ---- THORNVEIL PASS ----
  {
    id: 'thornveil_knight_1',
    name: 'Sir Aldric Vane',
    type: 'knight',
    emoji: '⚔️',
    regionId: 'thornveil',
    greeting: 'I rode through Thornveil Pass three days ago. Blasted place nearly swallowed my regiment. I need a map before my commander sends another unit in blind.',
    departurePositive: 'Excellent work. My men will march with confidence. You have my gratitude, cartographer.',
    departureNegative: 'This is… not what I described. I hope my soldiers are more observant than this parchment suggests.',
    clues: [
      {
        text: 'Mountains everywhere. I mean it — every direction I looked, stone. The entire perimeter is nothing but mountain, top to bottom, left to right. There is no gap in the outer ring.',
        tileType: 'mountain',
        gridX: 0,
        gridY: 0,
      },
      {
        text: 'There is a river cutting through — starts somewhere in the second or third column near the top and runs all the way south. By the bottom row it sits squarely in the fifth column.',
        tileType: 'river',
        gridX: 2,
        gridY: 1,
      },
      {
        text: 'Forest occupies the left-centre area — thick with moss, difficult to traverse. It fills the left portion of rows two through five, always inside the mountain ring.',
        tileType: 'forest',
        gridX: 1,
        gridY: 2,
      },
      {
        text: 'By the fourth row down, the river has drifted eastward — it was in the fourth column at that point. The forest still flanked it on the left.',
        tileType: 'river',
        gridX: 3,
        gridY: 3,
      },
    ],
    baseReward: 80,
  },
  {
    id: 'thornveil_mage_1',
    name: 'Velindra of the Pale Eye',
    type: 'mage',
    emoji: '🔮',
    regionId: 'thornveil',
    greeting: 'The pass calls to me in resonant frequencies. I have walked its stone corridors and felt the geography press against my thoughts. Let me share what the mountains confided.',
    departurePositive: 'The map sings with truth. I felt it the moment you laid the final tile. Extraordinary craft.',
    departureNegative: 'No, no. The geometries are wrong. The mountains weep when they are misrepresented. Can you not hear them?',
    clues: [
      {
        text: 'Stone dominates all. I sense mountain-essence at every corner — the northwest corner radiates the densest concentration of mountain energy I have ever encountered.',
        tileType: 'mountain',
        gridX: 0,
        gridY: 0,
      },
      {
        text: 'Water flows from the north, a silver thread. It enters the map at the third column from the left, at the very top — row one if you count from zero.',
        tileType: 'river',
        gridX: 2,
        gridY: 1,
      },
      {
        text: 'The forest breathes on the western side — I tasted pine and damp bark in rows two, three, four, and five. Always in columns one and two, sometimes three.',
        tileType: 'forest',
        gridX: 1,
        gridY: 3,
      },
      {
        text: 'At the sixth row — nearly the bottom — the river has curved to column four. Forest mingles with it there. The water and wood exchange memories.',
        tileType: 'river',
        gridX: 4,
        gridY: 5,
      },
    ],
    baseReward: 75,
  },
  {
    id: 'thornveil_ranger_1',
    name: 'Essa Coldbrook',
    type: 'ranger',
    emoji: '🏹',
    regionId: 'thornveil',
    greeting: "Thornveil Pass. Spent two weeks there tracking a missing trade caravan. Found the caravan — well, what was left. But I catalogued the terrain every day. Here's what I've got.",
    departurePositive: "That's a solid rendering. The proportions are right and the river drift is accurate. Good work.",
    departureNegative: "Hmm. That river placement is off. If someone navigates by this they'll walk straight into a rock face.",
    clues: [
      {
        text: 'The entire region is mountain-walled. No breaks, no passes except the one you enter through — and even that closes behind you in fog. Stone all around the edges.',
        tileType: 'mountain',
        gridX: 6,
        gridY: 0,
      },
      {
        text: 'River originates somewhere in the north-centre. I first crossed it at column two, row one. Cold water, fast current, runs roughly south-southeast.',
        tileType: 'river',
        gridX: 2,
        gridY: 1,
      },
      {
        text: 'Forest runs through the interior left side — columns one through three, rows two to five. Dense canopy, soft ground underfoot. Good cover.',
        tileType: 'forest',
        gridX: 2,
        gridY: 4,
      },
      {
        text: "By the bottom of the map, the river's settled into column four. That's where I lost the caravan tracks — the water erased everything.",
        tileType: 'river',
        gridX: 4,
        gridY: 6,
      },
    ],
    baseReward: 70,
  },

  // ---- SALTMERE COAST ----
  {
    id: 'saltmere_merchant_1',
    name: 'Orvyn Brassclasp',
    type: 'merchant',
    emoji: '💰',
    regionId: 'saltmere',
    greeting: "Saltmere. Lost three crates of spice silk to that cursed coast. I need a chart so my next factor doesn't make the same mistakes. I'll pay well for accuracy.",
    departurePositive: "Good. Very good. That village placement near the water is exactly right. I'll have my factor use this.",
    departureNegative: 'That dungeon marker is in completely the wrong place. My factor nearly died. I expect better.',
    clues: [
      {
        text: 'The entire northern half is sea. The top rows — you can practically hear the waves. Nothing but open water across all of row zero.',
        tileType: 'sea',
        gridX: 3,
        gridY: 0,
      },
      {
        text: 'There are two fishing villages along the coast — one at column two, row one, and one just west at column one, row two. The second is larger.',
        tileType: 'village',
        gridX: 2,
        gridY: 1,
      },
      {
        text: 'From row three southward it becomes forested. The forest spans almost the whole width — rows three through six, columns zero to six, with some sea peaking in at the upper right.',
        tileType: 'forest',
        gridX: 0,
        gridY: 3,
      },
      {
        text: 'There are dungeon entrances in the forest interior. I count them at column two row four, and forming a cluster at columns one, two, and three in row five.',
        tileType: 'dungeon',
        gridX: 2,
        gridY: 4,
      },
    ],
    baseReward: 85,
  },
  {
    id: 'saltmere_bard_1',
    name: 'Lyric Saltwhisper',
    type: 'bard',
    emoji: '🎶',
    regionId: 'saltmere',
    greeting: 'Oh, the Saltmere Coast! I have sung of it in seventeen inns and written two ballads about its particular shade of melancholy. The geography is practically a character unto itself.',
    departurePositive: "Beautiful. This map has *soul*. The villages sit like lonely pearls at the water's edge, just as I described.",
    departureNegative: "This map has all the poetry of a tax ledger. The dungeons are in completely the wrong place.",
    clues: [
      {
        text: 'Picture a coast where the sea dominates the entire top — an unbroken grey-blue expanse across the first row. Nothing but water, horizon to horizon.',
        tileType: 'sea',
        gridX: 0,
        gridY: 0,
      },
      {
        text: 'Two villages nestle like shy creatures at the waterline — one at the third column of the second row, one at the second column of the third row. Smoke from hearth fires.',
        tileType: 'village',
        gridX: 2,
        gridY: 1,
      },
      {
        text: 'Forest sweeps in from the south and west — by the fourth row you are entirely beneath canopy on the left side. The trees march all the way to the bottom.',
        tileType: 'forest',
        gridX: 1,
        gridY: 3,
      },
      {
        text: 'Beneath those beautiful trees hides something dark — dungeon mouths yawning in rows four and five. A whole little cluster of them, column two row four, and three in a row at row five.',
        tileType: 'dungeon',
        gridX: 2,
        gridY: 5,
      },
    ],
    baseReward: 65,
  },
  {
    id: 'saltmere_monster_1',
    name: 'Grix the Tide-Walker',
    type: 'monster',
    emoji: '🐙',
    regionId: 'saltmere',
    greeting: "Hmm. You are the map-owl. Good. Grix needs map of coast. Grix lives there but... Grix keeps getting lost in the forest-part. The trees all look same. You make map, yes?",
    departurePositive: "Yes! This is good map! Grix can find the dungeon-friends now. You understand coast-place very well for land-creature.",
    departureNegative: "No no no. Map wrong. Grix tried to use last map and walked into the sea. Grix does not like the sea. Too much memory.",
    clues: [
      {
        text: 'Top of place — all sea. Grix knows sea very well. Top row, all sea, no land. Sea is nice but also full of opinions.',
        tileType: 'sea',
        gridX: 5,
        gridY: 0,
      },
      {
        text: 'There are small-house-places near water. Two of them. Column two of second row. Column one and two of third row. Small-house creatures are friendly if you do not look hungry.',
        tileType: 'village',
        gridX: 1,
        gridY: 2,
      },
      {
        text: 'Big tree-place starts at fourth row. All of it. Left side of map from row three to bottom. Many trees. Grix bumped into many trees.',
        tileType: 'forest',
        gridX: 0,
        gridY: 3,
      },
      {
        text: 'Grix\'s friends live in the dark-under-ground holes. Hole at column two row four. More holes at row five — columns one, two, three. That is where Grix goes for dinner.',
        tileType: 'dungeon',
        gridX: 1,
        gridY: 5,
      },
    ],
    baseReward: 70,
  },

  // ---- ASHGRAVE DESERT ----
  {
    id: 'ashgrave_knight_1',
    name: 'Dame Petra Ironclad',
    type: 'knight',
    emoji: '🛡️',
    regionId: 'ashgrave',
    greeting: 'I led an expedition to Ashgrave last season. Lost two horses and a squire. What we found in those ruins justified the cost, but I need a map before I go back.',
    departurePositive: 'Precise work. The ruins cluster is exactly where I found it. You have a gift for the craft.',
    departureNegative: 'That is not what I described. The ruins are misplaced. I rode three days through heat for this.',
    clues: [
      {
        text: 'Desert everywhere — every single cell of that map is sand except for the ruins. Do not put anything else. No water, no forest. Just desert as the baseline, ruins on top.',
        tileType: 'desert',
        gridX: 0,
        gridY: 0,
      },
      {
        text: 'The first ruins I encountered were at column two, row one — a single crumbled tower sticking up from the sand like a broken tooth.',
        tileType: 'ruins',
        gridX: 2,
        gridY: 1,
      },
      {
        text: 'From there the ruins spread in a cross-pattern. Row two had three adjacent ruins: columns one, two, and three. Then another at column two in row three.',
        tileType: 'ruins',
        gridX: 1,
        gridY: 2,
      },
      {
        text: 'In the southern half — rows four through six — there is a second cluster. Column four in row four, then columns three, four, five in row five, and column four again in row six.',
        tileType: 'ruins',
        gridX: 4,
        gridY: 4,
      },
    ],
    baseReward: 90,
  },
  {
    id: 'ashgrave_mage_1',
    name: 'Oswin the Theorist',
    type: 'mage',
    emoji: '📚',
    regionId: 'ashgrave',
    greeting: 'Ashgrave! The very name makes my third eye water with excitement. I have studied the planar resonance of those ruins for six years. The geometry is profoundly, catastrophically wrong — and I love it.',
    departurePositive: 'Yes! The cross-pattern! The southern echo! You\'ve captured the impossible symmetry perfectly. Magnificent.',
    departureNegative: 'No, no, you\'ve put the southern cluster in the wrong position. The ancient builders would be deeply offended. Possibly literally — they may still be watching.',
    clues: [
      {
        text: 'The substrate is pure desert — not a drop of water, not a living plant. Everything that is not ruins is sand. Mark the whole grid desert first.',
        tileType: 'desert',
        gridX: 6,
        gridY: 6,
      },
      {
        text: 'The northern ruins form a cross. Single point at column two row one, expanding to a horizontal bar at row two (columns one, two, three), then back to a point at column two row three.',
        tileType: 'ruins',
        gridX: 2,
        gridY: 2,
      },
      {
        text: 'The southern ruins echo the northern ones but shifted east. Single ruin at column four row four, a horizontal bar at row five (columns three, four, five), single point at column four row six.',
        tileType: 'ruins',
        gridX: 3,
        gridY: 5,
      },
      {
        text: 'Here is the strangest thing — the two cross-patterns face each other like mirror images, but they are not quite mirrors. They are… reaching.',
        tileType: 'ruins',
        gridX: 4,
        gridY: 5,
      },
    ],
    baseReward: 80,
  },
  {
    id: 'ashgrave_bard_1',
    name: 'Canto Duskfall',
    type: 'bard',
    emoji: '🎭',
    regionId: 'ashgrave',
    greeting: 'The Ashgrave Desert! I spent a month there composing my masterwork — "Elegy for Geometry That Should Not Exist." The ruins inspired every verse. I know that landscape like my own heartbeat.',
    departurePositive: 'Oh, you beautiful owl. You\'ve captured the lonely geometry of it. Those two cross-patterns, facing each other across the sand. Perfect.',
    departureNegative: 'This is wrong. The ruins are scattered randomly. They have pattern — they have INTENTION. You\'ve made it look like someone dropped a bag of stones.',
    clues: [
      {
        text: 'Sand, sand, sand — the entire canvas is sand. That is the first truth of Ashgrave. Everything is desert until the ruins interrupt it. No exceptions.',
        tileType: 'desert',
        gridX: 3,
        gridY: 3,
      },
      {
        text: 'The northern complex: a single ruin at column two, row one. Then three in a horizontal line at row two — columns one, two, three. Then back to one at column two, row three. A cross, like a gravestone.',
        tileType: 'ruins',
        gridX: 2,
        gridY: 1,
      },
      {
        text: 'Then silence — pure desert at row four except for a single outlier ruin at column four.',
        tileType: 'ruins',
        gridX: 4,
        gridY: 4,
      },
      {
        text: 'The southern cross: row five has three ruins at columns three, four, five. Row six has one at column four. They reach northward toward the other cross, as if in conversation across the void.',
        tileType: 'ruins',
        gridX: 4,
        gridY: 5,
      },
    ],
    baseReward: 70,
  },

  // ---- MIREWOOD SWAMP ----
  {
    id: 'mirewood_ranger_1',
    name: 'Thorn Ashwick',
    type: 'ranger',
    emoji: '🌿',
    regionId: 'mirewood',
    greeting: "Mirewood. I track there regularly — poachers mostly, but sometimes things that aren't animals. The swamp has a centre. Something is in it. I need you to map it carefully.",
    departurePositive: "That's it. The lair sits exactly where I marked it in my field notes. Good map.",
    departureNegative: "The lair placement is off. That matters — you don't want to stumble onto a lair unprepared. I've seen what happens.",
    clues: [
      {
        text: 'Swamp on all borders — the outer edge of every row and column is swamp. The perimeter is completely waterlogged. Mark everything outside the forest ring as swamp.',
        tileType: 'swamp',
        gridX: 0,
        gridY: 0,
      },
      {
        text: 'Forest ring inside the swamp. It starts at column one row one and expands through rows two, three, four, five — always in columns one and two, sometimes three.',
        tileType: 'forest',
        gridX: 1,
        gridY: 1,
      },
      {
        text: 'The forest thickens in rows three and four — three columns wide there, columns one through three. That is the Vigil Formation the cartographers write about.',
        tileType: 'forest',
        gridX: 2,
        gridY: 3,
      },
      {
        text: 'Dead centre of the forest ring — column two, row three. That is where the lair is. You will know it by the silence. Everything else makes noise in a swamp.',
        tileType: 'lair',
        gridX: 2,
        gridY: 3,
      },
    ],
    baseReward: 80,
  },
  {
    id: 'mirewood_monster_1',
    name: 'Bogmaw',
    type: 'monster',
    emoji: '🐸',
    regionId: 'mirewood',
    greeting: "Bogmaw lives in Mirewood. Bogmaw needs map because Bogmaw keeps forgetting where the sleeping-old-thing is. It is embarrassing. Please do not tell anyone Bogmaw needs a map of Bogmaw's own home.",
    departurePositive: "Yes yes yes. That is right. The old-sleeping-thing is in the right place. Bogmaw will not embarrass self again. Thank you map-owl.",
    departureNegative: "That is wrong place for old-sleeping-thing. Bogmaw stepped on it by accident last winter. Very bad. Very bad indeed.",
    clues: [
      {
        text: 'All outside — all swamp. Big wet ring all around. Top row, bottom row, first column, last column — all swamp. Bogmaw knows because Bogmaw likes to patrol the outside.',
        tileType: 'swamp',
        gridX: 6,
        gridY: 6,
      },
      {
        text: 'Inside ring — trees. Forest trees, not swamp trees. They grow in a circle-shape. Start at row one column one. Keep going through rows two three four five.',
        tileType: 'forest',
        gridX: 1,
        gridY: 2,
      },
      {
        text: 'Column two row five — also forest. And column one row four, column two row four, column three row four, and column three row three. Many trees in middle-left.',
        tileType: 'forest',
        gridX: 1,
        gridY: 4,
      },
      {
        text: 'Old-sleeping-thing is at column two, row three. Middle of the forest circle. Bogmaw does not go near it. Bogmaw respects old-sleeping-thing. Bogmaw just wants to know where NOT to go.',
        tileType: 'lair',
        gridX: 2,
        gridY: 3,
      },
    ],
    baseReward: 75,
  },
  {
    id: 'mirewood_mage_1',
    name: 'Sybilla Dawngrove',
    type: 'mage',
    emoji: '🌙',
    regionId: 'mirewood',
    greeting: 'The Vigil Formation of Mirewood is one of the great unexplained mysteries of botanical geography. I have spent two seasons meditating within the forest ring, trying to understand what the trees are protecting.',
    departurePositive: 'The formation is captured perfectly — the concentric rings, the lair at the centre. You have made a map worthy of the mystery.',
    departureNegative: 'The lair is misplaced. The trees would never allow it to sit where you have marked it. Their roots would have smothered it.',
    clues: [
      {
        text: 'The entire outer boundary is swamp — rows zero and six, columns zero and six are completely saturated. The swamp forms a perfect frame.',
        tileType: 'swamp',
        gridX: 0,
        gridY: 6,
      },
      {
        text: 'Within the frame: forest, growing in a rough oval. Column one, rows one through five. Column two, rows two through five. Column three, rows three and four.',
        tileType: 'forest',
        gridX: 1,
        gridY: 1,
      },
      {
        text: 'The trees also appear in column three at row four — the eastern edge of the formation. And at column two, row five — the southern tip.',
        tileType: 'forest',
        gridX: 3,
        gridY: 4,
      },
      {
        text: 'At the precise centre — column two, row three — the trees part. There is a clearing of sorts. And in that clearing, something ancient breathes. I classify it as a lair, though that word feels insufficient.',
        tileType: 'lair',
        gridX: 2,
        gridY: 3,
      },
    ],
    baseReward: 85,
  },

  // ---- FROSTPEAK HEIGHTS ----
  {
    id: 'frostpeak_knight_1',
    name: 'Commander Brek Stoneholt',
    type: 'knight',
    emoji: '❄️',
    regionId: 'frostpeak',
    greeting: 'Frostpeak. Brutal country. I had a garrison stationed there and need an accurate map for supply route planning. The river is critical — get that right or the whole thing is useless.',
    departurePositive: 'The river course is accurate and the village is correctly placed. This will serve my garrison well.',
    departureNegative: "The river is in the wrong position. That's not a navigational inconvenience — that's men dying of thirst.",
    clues: [
      {
        text: 'Mountain everywhere. Like Thornveil but colder and more hostile. The entire perimeter and most of the interior is mountain. That is your baseline.',
        tileType: 'mountain',
        gridX: 0,
        gridY: 0,
      },
      {
        text: 'There is a small village at column three, row one — exactly one cell, right of centre in the second row. My garrison traded with them. Sturdy people.',
        tileType: 'village',
        gridX: 3,
        gridY: 1,
      },
      {
        text: 'The village has a river nearby. It runs from around column four row two, then bends west through row three — covering columns two, three, and four.',
        tileType: 'river',
        gridX: 4,
        gridY: 2,
      },
      {
        text: 'By row four the river has bent further west — sitting in columns one and two. Then row five it is only at column one. After that, nothing.',
        tileType: 'river',
        gridX: 1,
        gridY: 4,
      },
    ],
    baseReward: 85,
  },
  {
    id: 'frostpeak_merchant_1',
    name: 'Yuna Frosttrader',
    type: 'merchant',
    emoji: '🧊',
    regionId: 'frostpeak',
    greeting: 'Frostpeak Heights — brutal trade route but the village there produces the finest coldweave wool in the known world. I need a map so my mules stop falling into the river.',
    departurePositive: 'The village and river are correctly placed. My mules will thank you, even if they cannot articulate it.',
    departureNegative: 'The river placement is wrong. My mules have opinions about accuracy, and so do I.',
    clues: [
      {
        text: 'All mountain, background throughout. The only things that break the mountain monotony are a village, a river, and more mountain.',
        tileType: 'mountain',
        gridX: 5,
        gridY: 5,
      },
      {
        text: 'The trading village sits at column three, row one — slightly right of centre, near the top. That is where the wool market is. That is where the money is.',
        tileType: 'village',
        gridX: 3,
        gridY: 1,
      },
      {
        text: 'Village also spreads to column two row two and column three row two — it is a small cluster, not a single point. The market square is at the centre.',
        tileType: 'village',
        gridX: 2,
        gridY: 2,
      },
      {
        text: 'The river comes from the village area. Column four row two, then west along row three at columns two three four, then columns one two at row four, then just column one at row five. It bends like a shepherd\'s crook.',
        tileType: 'river',
        gridX: 2,
        gridY: 3,
      },
    ],
    baseReward: 80,
  },
  {
    id: 'frostpeak_bard_1',
    name: 'Fenwick Iceharp',
    type: 'bard',
    emoji: '🎼',
    regionId: 'frostpeak',
    greeting: 'Ah, Frostpeak! I wrote my famous ballad "The River\'s Crook and the Village It Loved" about this very region. I know every bend of that river intimately. Ask me anything.',
    departurePositive: "The crook of the river, the lonely village — you've mapped it exactly as I sang it. Magnificent. I'll dedicate my next ballad to you.",
    departureNegative: "This is not the river from my ballad. This is some other, inferior river. The village is weeping.",
    clues: [
      {
        text: 'Mountain is the canvas — every edge, every corner, the entire background. Cold grey stone from horizon to horizon. The drama lives in what interrupts it.',
        tileType: 'mountain',
        gridX: 0,
        gridY: 6,
      },
      {
        text: 'A village — small, brave, impossibly warm — sits at column three row one. It extends to column two and three of row two. Two cells that hold an entire community.',
        tileType: 'village',
        gridX: 3,
        gridY: 1,
      },
      {
        text: 'The river begins at column four of row two — it is young there, narrow. Then at row three it widens across columns two, three, four. The chorus of my ballad describes this exact moment.',
        tileType: 'river',
        gridX: 4,
        gridY: 2,
      },
      {
        text: 'Then the river bends west and thins — columns one and two at row four, then only column one at row five. It dies in the mountain, swallowed by stone. That is the tragic ending of my ballad.',
        tileType: 'river',
        gridX: 1,
        gridY: 5,
      },
    ],
    baseReward: 70,
  },
];

export const LORE_ENTRIES: LoreEntry[] = [
  {
    id: 'lore_1',
    unlockedOnDay: 3,
    text: 'A cartographer\'s note, found tucked inside a returned map: "The mountains move. Not in any single lifetime — but move. I have compared charts from three generations and the deviation is measurable. Something beneath pushes them. I do not know what."',
  },
  {
    id: 'lore_2',
    unlockedOnDay: 5,
    text: 'Overheard from a knight who did not know you were listening: "The ruins at Ashgrave — the geometry. I have seen those angles before. In dreams I cannot remember upon waking. My sword arm aches near them."',
  },
  {
    id: 'lore_3',
    unlockedOnDay: 7,
    text: 'A torn page from an unknown journal: "Third expedition to Mirewood. The lair at the centre is not empty. It has never been empty. We thought it was dormant. The trees knew better. The trees have always known."',
  },
  {
    id: 'lore_4',
    unlockedOnDay: 10,
    text: 'A message delivered by a bird you do not recognise, addressed to no one: "The five regions are not separate. They are fingers on a hand. When the hand closes — and it is closing — everything between the fingers will be crushed."',
  },
  {
    id: 'lore_5',
    unlockedOnDay: 14,
    text: 'Written on the back of a map returned with payment but no customer: "Your maps are more accurate than you know. You are not drawing the land as it is — you are drawing the land as it wants to be remembered. There is a difference. The difference matters."',
  },
  {
    id: 'lore_6',
    unlockedOnDay: 18,
    text: 'A ranger arrived at midnight, shaking. She said nothing, left a sketch on the counter, and departed. The sketch showed all five regions arranged in a circle, connected by rivers that do not appear on any known map. At the centre of the circle: a question mark, and beneath it, in her handwriting: "It is awake."',
  },
  {
    id: 'lore_7',
    unlockedOnDay: 22,
    text: 'From the Saltmere maritime archive, water-damaged: "...the sea there does not follow tidal patterns. It follows something else. We tracked the anomaly for six years and determined the source is not the moon. The source is directional. The source is inland. The source is—" The rest is illegible.',
  },
  {
    id: 'lore_8',
    unlockedOnDay: 28,
    text: 'A small card left under your door. No ink — the words are pressed into the parchment by something sharp: "You have been mapping a dream. The dreamer is nearly awake. When it opens its eyes, it will look for the last place it remembers. Your shop is built on that place. You should know this. You deserve to know this. — A friend who cannot give their name."',
  },
];
