// ============================================================
//  Game Data — customers, puzzles, upgrades
//  Grid: 6 cols × 6 rows. col=0 is West, col=5 is East.
//                          row=0 is North, row=5 is South.
// ============================================================

export const TILE_TYPES = {
  plains:   { id: 'plains',   label: 'Plains',   emoji: '🌾', desc: 'Open flatlands'         },
  forest:   { id: 'forest',   label: 'Forest',   emoji: '🌲', desc: 'Dense woodland'          },
  mountain: { id: 'mountain', label: 'Mountain', emoji: '⛰️',  desc: 'Rocky peaks'             },
  river:    { id: 'river',    label: 'River',    emoji: '🌊', desc: 'Flowing water'            },
  lake:     { id: 'lake',     label: 'Lake',     emoji: '💧', desc: 'Still deep water'         },
  town:     { id: 'town',     label: 'Town',     emoji: '🏘️',  desc: 'A settled community'     },
  dungeon:  { id: 'dungeon',  label: 'Dungeon',  emoji: '🗝️',  desc: 'Underground labyrinth'   },
  ruins:    { id: 'ruins',    label: 'Ruins',    emoji: '🏚️',  desc: 'Ancient remains'          },
  volcano:  { id: 'volcano',  label: 'Volcano',  emoji: '🌋', desc: 'Active volcano'           },
  swamp:    { id: 'swamp',    label: 'Swamp',    emoji: '🌿', desc: 'Murky wetlands'           },
  castle:   { id: 'castle',   label: 'Castle',   emoji: '🏰', desc: 'Fortified stronghold'     },
  desert:   { id: 'desert',   label: 'Desert',   emoji: '🏜️',  desc: 'Arid wasteland'           },
};

// ============================================================
//  NIGHTS
// ============================================================
export const NIGHTS = [

  // ──────────────────────────────────────────────────────────
  //  NIGHT 1
  // ──────────────────────────────────────────────────────────
  {
    id: 1,
    intro: 'The rain taps softly on the windowpane. Your candles flicker. The first customer of the evening steps through the door…',
    worldShift: null,
    returnVisitors: [],
    customers: [
      {
        id: 'c1_n1',
        name: 'Sir Aldric',
        type: 'Weary Knight',
        emoji: '⚔️',
        intro: 'A heavy-armored knight collapses into the chair across from you. He smells of pine smoke and old leather.',
        testimony: [
          '"Stonehaven — that\'s my home town. It sits in the south, close to the eastern edge of the region."',
          '"I walked north from there, deep into a dense forest. Took half a day to get through."',
          '"Beyond the forest, I found a river. It ran east to west right across my path."',
          '"On the far bank, the mountains began. The peaks stretch all along the northern horizon."',
          '"The dungeon entrance was carved into the base of the central mountain — right where the river bends northward."',
        ],
        anchors: [
          { col: 4, row: 5, type: 'town', label: 'Stonehaven', fixed: true },
        ],
        solution: [
          { col: 4, row: 4, type: 'forest',   points: 12, label: 'Forest (east)'    },
          { col: 3, row: 4, type: 'forest',   points: 10, label: 'Forest (mid)'     },
          { col: 3, row: 3, type: 'forest',   points: 10, label: 'Forest (north)'   },
          { col: 2, row: 2, type: 'river',    points: 15, label: 'River (west)'     },
          { col: 3, row: 2, type: 'river',    points: 20, label: 'River (bend)'     },
          { col: 4, row: 2, type: 'river',    points: 15, label: 'River (east)'     },
          { col: 2, row: 0, type: 'mountain', points: 12, label: 'Mountains (west)' },
          { col: 3, row: 0, type: 'mountain', points: 15, label: 'Mountains (mid)'  },
          { col: 4, row: 0, type: 'mountain', points: 12, label: 'Mountains (east)' },
          { col: 3, row: 1, type: 'dungeon',  points: 30, label: 'The Dungeon'      },
        ],
        availableTiles: ['forest', 'mountain', 'river', 'dungeon', 'plains'],
        successGold: 45,
        failureGold: 12,
        successTrust: 12,
        failureTrust: -8,
        successMessage: '"By the stars, this is perfect! I owe you a drink, master owl." He tucks the map into his saddlebag with a satisfied grin.',
        failureMessage: '"I... suppose this will do." He squints at the map uncertainly, then pockets it with a sigh.',
      },

      {
        id: 'c2_n1',
        name: 'Mira Duskhollow',
        type: 'Travelling Merchant',
        emoji: '🛒',
        intro: 'A rosy-cheeked merchant sets a jingling coin-purse on your desk and pulls out a crumpled napkin covered in scrawled notes.',
        testimony: [
          '"I run goods out of Redbridge. Lovely little town — southwest corner of the valley, right on the edge."',
          '"There\'s a thick forest north of Redbridge. Winds up the western side. Runs about two days through."',
          '"A river cuts right through that forest, west to east."',
          '"East of the forest the land opens up — wide plains. Very flat. Very boring."',
          '"In the middle of those plains sits Valorgate. Big city, tall walls. Two days east of where the forest ends."',
        ],
        anchors: [
          { col: 0, row: 5, type: 'town', label: 'Redbridge', fixed: true },
        ],
        solution: [
          { col: 0, row: 4, type: 'forest', points: 12, label: 'Forest (south)'  },
          { col: 0, row: 3, type: 'forest', points: 12, label: 'Forest (west 1)' },
          { col: 1, row: 3, type: 'forest', points: 10, label: 'Forest (west 2)' },
          { col: 1, row: 2, type: 'river',  points: 18, label: 'River (west)'    },
          { col: 2, row: 2, type: 'river',  points: 15, label: 'River (mid)'     },
          { col: 3, row: 3, type: 'plains', points: 10, label: 'Plains (near)'   },
          { col: 4, row: 3, type: 'plains', points: 10, label: 'Plains (far)'    },
          { col: 4, row: 2, type: 'castle', points: 28, label: 'Valorgate'       },
        ],
        availableTiles: ['forest', 'river', 'plains', 'castle', 'town'],
        successGold: 40,
        failureGold: 10,
        successTrust: 10,
        failureTrust: -6,
        successMessage: '"Excellent! The road to Valorgate shall be smooth indeed. You\'ll have my business again, I promise!" She drops a bonus coin on the desk.',
        failureMessage: '"Hmm. The river seems a bit... off. But I\'ll manage." She rolls up the map with a doubtful look.',
      },

      {
        id: 'c3_n1',
        name: 'Thornwood',
        type: 'Elven Ranger',
        emoji: '🏹',
        intro: 'A lithe elf with mud-stained boots and autumn leaves in her hair perches on the edge of the chair, barely touching it.',
        testimony: [
          '"Moonhaven — my village — is in the north, on the western side. Very peaceful, very hidden."',
          '"Directly south of Moonhaven there are open plains for a couple of days\' walk."',
          '"The plains turn wet and murky further south. A great swamp begins around the midpoint of the region."',
          '"In the eastern part of the swamp, half-sunken in mud, there are ancient ruins. No one goes there. Except me."',
          '"Along the entire eastern border the land rises into mountains. They block the sunrise every morning."',
        ],
        anchors: [
          { col: 1, row: 0, type: 'town', label: 'Moonhaven', fixed: true },
        ],
        solution: [
          { col: 1, row: 1, type: 'plains',   points: 10, label: 'Plains (north)'    },
          { col: 1, row: 2, type: 'plains',   points: 10, label: 'Plains (south)'    },
          { col: 1, row: 3, type: 'swamp',    points: 14, label: 'Swamp (west)'      },
          { col: 2, row: 3, type: 'swamp',    points: 14, label: 'Swamp (mid)'       },
          { col: 2, row: 4, type: 'swamp',    points: 12, label: 'Swamp (deep)'      },
          { col: 3, row: 4, type: 'ruins',    points: 28, label: 'Ancient Ruins'     },
          { col: 5, row: 1, type: 'mountain', points: 12, label: 'East Mountains (N)'},
          { col: 5, row: 2, type: 'mountain', points: 12, label: 'East Mountains (M)'},
          { col: 5, row: 3, type: 'mountain', points: 12, label: 'East Mountains (S)'},
        ],
        availableTiles: ['plains', 'swamp', 'ruins', 'mountain', 'forest'],
        successGold: 42,
        failureGold: 10,
        successTrust: 11,
        failureTrust: -7,
        successMessage: '"Surprisingly accurate for a young cartographer. The ruins are exactly there." She gives you a rare approving nod.',
        failureMessage: '"The swamp placement is… well, close enough. I\'ll find my way." She disappears into the rainy night.',
      },
    ],
  },

  // ──────────────────────────────────────────────────────────
  //  NIGHT 2
  // ──────────────────────────────────────────────────────────
  {
    id: 2,
    intro: 'The second night begins. Word of your shop has spread — the queue outside is longer. And there are whispers of strange things on the roads…',
    worldShift: 'Travelers arriving tonight speak of something unsettling: the Whispering Wood — a forest in the mid-eastern valley — has reportedly moved overnight. Hunters who knew every trail found themselves lost. Maps drawn of that region just last week are already wrong.',
    returnVisitors: [
      {
        name: 'Sir Aldric',
        emoji: '⚔️',
        message: '"I found the dungeon! Your map was nearly perfect — though the river was placed a touch too far east. I forgave the error after the dragon dropped all its gold." He laughs and drops a bonus coin.',
        bonusGold: 15,
      },
    ],
    customers: [
      {
        id: 'c1_n2',
        name: 'Brother Oswin',
        type: 'Wandering Monk',
        emoji: '📿',
        intro: 'A dusty monk carefully sets down a walking staff and folds his hands on your desk.',
        testimony: [
          '"I departed from the Monastery of Salt — it\'s in the northwest corner of the hills."',
          '"East of the Monastery, a volcano dominates the horizon. Smoking constantly. Very dramatic."',
          '"South of the volcano, the land drops into a great lake. Very still, very deep."',
          '"A town called Crestford sits on the southern shore of that lake."',
          '"From Crestford I walked east two days across open plains to reach your city."',
        ],
        anchors: [
          { col: 0, row: 0, type: 'ruins', label: 'Monastery', fixed: true },
        ],
        solution: [
          { col: 2, row: 0, type: 'volcano',  points: 25, label: 'The Volcano'     },
          { col: 2, row: 1, type: 'lake',     points: 20, label: 'The Great Lake'  },
          { col: 2, row: 2, type: 'lake',     points: 15, label: 'Lake (south)'    },
          { col: 2, row: 3, type: 'town',     points: 22, label: 'Crestford'       },
          { col: 3, row: 3, type: 'plains',   points: 10, label: 'Plains (west)'   },
          { col: 4, row: 3, type: 'plains',   points: 10, label: 'Plains (east)'   },
        ],
        availableTiles: ['volcano', 'lake', 'town', 'plains', 'mountain', 'river'],
        successGold: 48,
        failureGold: 12,
        successTrust: 12,
        failureTrust: -8,
        successMessage: '"The Great Cartographer blesses you, friend. This is most precise." He bows and shuffles out into the rain.',
        failureMessage: '"I pray the lake is in the right place… else I may become unexpectedly baptized." He sighs and takes the map.',
      },

      {
        id: 'c2_n2',
        name: 'Grix',
        type: 'Goblin Scout',
        emoji: '👺',
        intro: 'A green goblin leaps onto the chair, sitting cross-legged. He pulls out a sock from which he retrieves his payment.',
        testimony: [
          '"Big rock place — castle — in the middle of the north edge. Lots of humans with pointy sticks."',
          '"Two days south of the castle: forest forest forest. Very thick. Scary noises at night."',
          '"East of the forest — river! Wide river, runs north to south along eastern side."',
          '"South of the forest: desert. Why desert so close to forest? Nobody knows! Nobody!"',
          '"In the desert: ruins. Old old ruins. Full of treasure. Grix knows. Grix checked."',
        ],
        anchors: [
          { col: 3, row: 0, type: 'castle', label: 'Iron Citadel', fixed: true },
        ],
        solution: [
          { col: 3, row: 2, type: 'forest',  points: 15, label: 'Forest (mid)'   },
          { col: 2, row: 2, type: 'forest',  points: 12, label: 'Forest (west)'  },
          { col: 4, row: 2, type: 'forest',  points: 12, label: 'Forest (east)'  },
          { col: 5, row: 1, type: 'river',   points: 15, label: 'River (north)'  },
          { col: 5, row: 2, type: 'river',   points: 15, label: 'River (south)'  },
          { col: 2, row: 4, type: 'desert',  points: 15, label: 'Desert (west)'  },
          { col: 3, row: 4, type: 'desert',  points: 12, label: 'Desert (east)'  },
          { col: 3, row: 5, type: 'ruins',   points: 28, label: 'Desert Ruins'   },
        ],
        availableTiles: ['forest', 'river', 'desert', 'ruins', 'plains'],
        successGold: 35,
        failureGold: 8,
        successTrust: 10,
        failureTrust: -5,
        successMessage: '"OOH! Good map! Very good map! Grix will find treasure for sure!" He rockets out the door.',
        failureMessage: '"Hmmm. This look… mostly right? Grix hopes." He eyes it suspiciously then pockets it.',
      },

      {
        id: 'c3_n2',
        name: 'Lady Veradis',
        type: 'Sorceress',
        emoji: '🔮',
        intro: 'A sorceress in deep violet robes sits down without being invited. A faint purple shimmer surrounds her hands.',
        testimony: [
          '"I require a map of the Eastern Reaches. My tower is on the far eastern edge, in the south."',
          '"North of my tower stretches a vast swamp — it covers much of the eastern half of the region."',
          '"In the centre of the swamp lies a lake. Ancient. Perfectly circular. Magically significant."',
          '"West of the swamp, the terrain rises into a mountain range running north to south."',
          '"Between the mountains and the swamp, in a narrow valley, there is a dungeon. I need to know exactly where."',
        ],
        anchors: [
          { col: 5, row: 5, type: 'castle', label: 'Veradis Tower', fixed: true },
        ],
        solution: [
          { col: 4, row: 4, type: 'swamp',    points: 12, label: 'Swamp (south)'   },
          { col: 5, row: 4, type: 'swamp',    points: 12, label: 'Swamp (east)'    },
          { col: 4, row: 3, type: 'swamp',    points: 12, label: 'Swamp (mid)'     },
          { col: 5, row: 3, type: 'swamp',    points: 10, label: 'Swamp (mid-e)'   },
          { col: 4, row: 2, type: 'swamp',    points: 10, label: 'Swamp (north)'   },
          { col: 5, row: 2, type: 'lake',     points: 25, label: 'Circular Lake'   },
          { col: 3, row: 2, type: 'mountain', points: 14, label: 'Mountains (N)'   },
          { col: 3, row: 3, type: 'mountain', points: 14, label: 'Mountains (S)'   },
          { col: 3, row: 4, type: 'dungeon',  points: 30, label: 'The Valley Dungeon' },
        ],
        availableTiles: ['swamp', 'lake', 'mountain', 'dungeon', 'plains'],
        successGold: 55,
        failureGold: 15,
        successTrust: 14,
        failureTrust: -10,
        successMessage: '"Acceptable. You have talent — for an owl." She sweeps out with the map, her robes trailing purple sparks.',
        failureMessage: '"This is… imprecise." A dangerous glint in her eye. "I shall… manage." The temperature drops slightly as she leaves.',
      },

      {
        id: 'c4_n2',
        name: 'Barnabus Crank',
        type: 'Retired Adventurer',
        emoji: '🍺',
        intro: 'A stout dwarf with a magnificent braided beard drops into the chair. He smells of pipe-smoke and honeywine.',
        testimony: [
          '"Listen here, I\'ve been adventuring forty years, I know my directions. Town of Boulderkeep: middle of the southern edge."',
          '"North of Boulderkeep, straight up, is a forest. Not a big one. Two days maybe."',
          '"The forest gives way to mountains. There\'s a whole range of \'em running east to west."',
          '"In the mountains — this is the important bit — there\'s a volcano. Old one. Dormant. Mostly."',
          '"And on the east side of those mountains, there\'s a river running south."',
        ],
        anchors: [
          { col: 2, row: 5, type: 'town', label: 'Boulderkeep', fixed: true },
        ],
        solution: [
          { col: 2, row: 4, type: 'forest',   points: 15, label: 'Forest (south)' },
          { col: 2, row: 3, type: 'forest',   points: 12, label: 'Forest (north)' },
          { col: 1, row: 1, type: 'mountain', points: 12, label: 'Mountains (W)'  },
          { col: 2, row: 1, type: 'mountain', points: 15, label: 'Mountains (M)'  },
          { col: 3, row: 1, type: 'mountain', points: 12, label: 'Mountains (E)'  },
          { col: 2, row: 0, type: 'volcano',  points: 25, label: 'Dormant Volcano'},
          { col: 4, row: 1, type: 'river',    points: 18, label: 'Eastern River'  },
          { col: 4, row: 2, type: 'river',    points: 14, label: 'River (south)'  },
        ],
        availableTiles: ['forest', 'mountain', 'volcano', 'river', 'plains'],
        successGold: 42,
        failureGold: 10,
        successTrust: 11,
        failureTrust: -6,
        successMessage: '"Ha! Now THAT\'S a proper map! I knew you were good." He claps you on the back hard enough to ruffle your feathers.',
        failureMessage: '"Close enough for an old dwarf, I suppose. Mountains are mountains." He shrugs and tucks it away.',
      },
    ],
  },

  // ──────────────────────────────────────────────────────────
  //  NIGHT 3
  // ──────────────────────────────────────────────────────────
  {
    id: 3,
    intro: 'The third night. The city outside murmurs with strange rumours. Several customers tonight mention something about a stone — a glowing stone that no map has ever shown…',
    worldShift: 'The River Solan has vanished. In its place: a desert. Overnight. Witnesses are baffled. Scholars speak of "geographic unwriting" — as if someone is erasing the world and drawing it again. And every witness mentions, quietly, a glow from somewhere north.',
    returnVisitors: [
      {
        name: 'Thornwood',
        emoji: '🏹',
        message: '"The ruins were exactly right. And something strange — there was a faint glow coming from the swamp that night. Didn\'t think much of it then… but now others speak of the same glow, further north."',
        bonusGold: 12,
      },
    ],
    customers: [
      {
        id: 'c1_n3',
        name: 'Captain Renna',
        type: 'Ship Captain',
        emoji: '⚓',
        intro: 'A sea-tanned captain with a compass tattooed on her forearm sits down, her expression grave.',
        testimony: [
          '"My port — Harrow\'s End — is on the southern coast. Far west. Sea to the south of it."',
          '"North of the port: open plains for two days, then a river running east to west."',
          '"East of the river, there is a great forest. Very old. The trees whisper."',
          '"In that forest: a castle. Ancient. No kingdom claims it. I\'ve charted it from a distance."',
          '"North of the forest, mountains. And somewhere in those mountains… something glows at night."',
        ],
        anchors: [
          { col: 0, row: 5, type: 'town', label: "Harrow's End", fixed: true },
        ],
        solution: [
          { col: 0, row: 4, type: 'plains',   points: 10, label: 'Plains (near)'    },
          { col: 0, row: 3, type: 'plains',   points: 10, label: 'Plains (far)'     },
          { col: 0, row: 2, type: 'river',    points: 18, label: 'River (west)'     },
          { col: 1, row: 2, type: 'river',    points: 15, label: 'River (mid)'      },
          { col: 2, row: 2, type: 'river',    points: 12, label: 'River (east)'     },
          { col: 2, row: 3, type: 'forest',   points: 14, label: 'Forest (south)'   },
          { col: 2, row: 1, type: 'forest',   points: 14, label: 'Forest (north)'   },
          { col: 3, row: 2, type: 'forest',   points: 12, label: 'Forest (east)'    },
          { col: 3, row: 1, type: 'castle',   points: 25, label: 'The Ancient Castle' },
          { col: 2, row: 0, type: 'mountain', points: 15, label: 'Mountains'        },
          { col: 3, row: 0, type: 'mountain', points: 15, label: 'Northern Peak'    },
        ],
        availableTiles: ['plains', 'river', 'forest', 'castle', 'mountain'],
        successGold: 52,
        failureGold: 14,
        successTrust: 13,
        failureTrust: -9,
        successMessage: '"The castle is perfectly placed. And that glow… I have a terrible feeling about what it might be." She leaves looking troubled.',
        failureMessage: '"The forest is a bit misplaced, but close enough for navigation. Stay safe, cartographer."',
      },

      {
        id: 'c2_n3',
        name: 'Zephra',
        type: 'Oracle\'s Apprentice',
        emoji: '🌙',
        intro: 'A young person in midnight robes unfurls a silk cloth on your desk, then says nothing for a full minute before speaking.',
        testimony: [
          '"The Oracle\'s Spire — my home — stands at the northern edge, dead centre."',
          '"A great lake surrounds the Spire on three sides — north, east, and west. We are nearly an island."',
          '"South of the lake there are dense forests — they stretch nearly to the midpoint of the region."',
          '"At the midpoint, east of centre, there is a volcano. It rumbles every new moon."',
          '"Ruins circle the volcano at a distance — old enough that no one remembers who built them."',
        ],
        anchors: [
          { col: 3, row: 0, type: 'castle', label: "Oracle's Spire", fixed: true },
        ],
        solution: [
          { col: 2, row: 0, type: 'lake',   points: 15, label: 'Lake (west)'     },
          { col: 4, row: 0, type: 'lake',   points: 15, label: 'Lake (east)'     },
          { col: 2, row: 1, type: 'forest', points: 14, label: 'Forest (west)'   },
          { col: 3, row: 1, type: 'forest', points: 14, label: 'Forest (mid)'    },
          { col: 4, row: 1, type: 'forest', points: 12, label: 'Forest (east)'   },
          { col: 3, row: 2, type: 'forest', points: 12, label: 'Forest (south)'  },
          { col: 4, row: 3, type: 'volcano',points: 25, label: 'The Volcano'     },
          { col: 3, row: 4, type: 'ruins',  points: 20, label: 'Ruins (south)'   },
          { col: 5, row: 3, type: 'ruins',  points: 18, label: 'Ruins (east)'    },
          { col: 4, row: 4, type: 'ruins',  points: 18, label: 'Ruins (near V)'  },
        ],
        availableTiles: ['lake', 'forest', 'volcano', 'ruins', 'plains'],
        successGold: 50,
        failureGold: 13,
        successTrust: 13,
        failureTrust: -8,
        successMessage: '"The Oracle foresaw your accuracy. The ruins are precisely placed." She pauses. "She also says: the Cartographer\'s Stone is real. Be careful."',
        failureMessage: '"The Oracle says: the map is imperfect, like all things. The stone still calls."',
      },

      {
        id: 'c3_n3',
        name: 'Halvard',
        type: 'Mountain Hermit',
        emoji: '🧙',
        intro: 'An ancient man wrapped in furs, with snow still in his beard, stares at your candles for a long moment before sitting.',
        testimony: [
          '"I live in the far north — northwest corner. Just me, the rocks, and the cold."',
          '"East of me, the mountains continue all along the northern edge."',
          '"Below the mountains to the south: a long east-west river."',
          '"I found something last month — east of centre, one day south of the northern mountains — a stone that glows. It pulses like a heartbeat. I dug around it. The ground feels… wrong there."',
          '"South of that strange place, the forest begins and thickens as you go south."',
        ],
        anchors: [
          { col: 0, row: 0, type: 'ruins', label: "Halvard's Hut", fixed: true },
        ],
        solution: [
          { col: 1, row: 0, type: 'mountain', points: 12, label: 'Mountains (E1)'    },
          { col: 2, row: 0, type: 'mountain', points: 12, label: 'Mountains (E2)'    },
          { col: 3, row: 0, type: 'mountain', points: 12, label: 'Mountains (E3)'    },
          { col: 1, row: 1, type: 'river',    points: 15, label: 'River (west)'      },
          { col: 2, row: 1, type: 'river',    points: 18, label: 'River (mid)'       },
          { col: 3, row: 1, type: 'river',    points: 15, label: 'River (east)'      },
          { col: 3, row: 2, type: 'dungeon',  points: 35, label: '✦ The Glowing Stone' },
          { col: 3, row: 3, type: 'forest',   points: 14, label: 'Forest (near)'     },
          { col: 3, row: 4, type: 'forest',   points: 12, label: 'Forest (deep)'     },
          { col: 2, row: 3, type: 'forest',   points: 12, label: 'Forest (west)'     },
        ],
        availableTiles: ['mountain', 'river', 'dungeon', 'forest', 'plains'],
        successGold: 55,
        failureGold: 14,
        successTrust: 14,
        failureTrust: -10,
        successMessage: '"Yes. Yes, that\'s exactly it. Right there." He points to the dungeon tile with a trembling finger. "That\'s where it is. Whatever it is — it\'s been moving things. Moving the whole world."',
        failureMessage: '"Close… but not quite. I don\'t think the stone wants to be found." He leaves without another word.',
      },

      {
        id: 'c4_n3',
        name: 'Luma',
        type: 'Fairy Cartographer',
        emoji: '🧚',
        intro: 'A thumb-sized fairy lands on your desk in a burst of golden sparks. She appears to have her own tiny map.',
        testimony: [
          '"I\'ve been mapping the Glimmer Vale for fifty years! The Vale is in the centre of the whole region — truly the heart of it."',
          '"It\'s surrounded by forest on the west and south — a great ring of trees."',
          '"The eastern side of the Vale has a river running north to south."',
          '"To the north of the Vale: plains, then more mountains."',
          '"And in the centre of the Vale itself — this is the secret — there is a dungeon entrance. Very old. Pulls at the magic in my wings."',
        ],
        anchors: [
          { col: 3, row: 3, type: 'plains', label: 'Glimmer Vale', fixed: true },
        ],
        solution: [
          { col: 2, row: 3, type: 'forest',   points: 14, label: 'Forest (west)'    },
          { col: 2, row: 4, type: 'forest',   points: 14, label: 'Forest (SW)'      },
          { col: 3, row: 4, type: 'forest',   points: 12, label: 'Forest (south)'   },
          { col: 4, row: 4, type: 'forest',   points: 10, label: 'Forest (SE)'      },
          { col: 4, row: 3, type: 'river',    points: 18, label: 'River (south)'    },
          { col: 4, row: 2, type: 'river',    points: 15, label: 'River (north)'    },
          { col: 3, row: 2, type: 'plains',   points: 10, label: 'Plains (north)'   },
          { col: 2, row: 1, type: 'mountain', points: 14, label: 'Mountains (W)'    },
          { col: 3, row: 1, type: 'mountain', points: 14, label: 'Mountains (M)'    },
          { col: 3, row: 3, type: 'dungeon',  points: 30, label: 'Vale Dungeon'     },
        ],
        availableTiles: ['forest', 'river', 'plains', 'mountain', 'dungeon'],
        successGold: 48,
        failureGold: 12,
        successTrust: 12,
        failureTrust: -7,
        successMessage: '"Brilliant! You found the dungeon! I\'ve been trying to map that for twenty years and I\'m TINY — I can\'t reach the keyhole!" She does a celebratory loop-the-loop.',
        failureMessage: '"Mmm. The forest ring is a little off but the Vale is there. Good enough!" She zooms out trailing sparks.',
      },

      {
        id: 'c5_n3',
        name: 'The Stranger',
        type: 'Unknown',
        emoji: '🌑',
        intro: 'The last customer of the night enters without the bell ringing. They wear a dark hood and carry a single black candle. They say nothing — they simply slide a piece of parchment across your desk.',
        testimony: [
          '"[The parchment reads:] The Cartographer\'s Stone is at the centre of the map. It has always been there."',
          '"[The parchment continues:] Every map ever drawn contains it, but every cartographer places it somewhere else — because the Stone shifts things around it to hide."',
          '"[The text changes colour:] Place the Stone at position (col 3, row 3). That is where it truly lies."',
          '"[Final line, in a hand that trembles:] It will stop shifting the world once someone maps it accurately. Once and for all."',
          '"[They push three heavy coins across the desk and leave before you can speak.]"',
        ],
        anchors: [],
        solution: [
          { col: 3, row: 3, type: 'dungeon', points: 100, label: '✦ The Cartographer\'s Stone' },
          { col: 2, row: 3, type: 'forest',  points: 15,  label: 'Forest (west)' },
          { col: 4, row: 3, type: 'river',   points: 15,  label: 'River (east)'  },
          { col: 3, row: 2, type: 'plains',  points: 15,  label: 'Plains (north)'},
          { col: 3, row: 4, type: 'swamp',   points: 15,  label: 'Swamp (south)' },
        ],
        availableTiles: ['dungeon', 'forest', 'river', 'plains', 'swamp', 'mountain', 'ruins'],
        successGold: 100,
        failureGold: 30,
        successTrust: 20,
        failureTrust: -5,
        successMessage: 'As you place the final tile, the shop shudders. Your ink bottles rattle. Then — silence. The rain outside stops. A warm golden light drifts through the window. Somewhere in the world, the Cartographer\'s Stone has been found at last.',
        failureMessage: 'The map is incomplete. The Stone remains unmapped. The world will continue to shift — but perhaps a little less, now that someone is trying.',
      },
    ],
  },
];

// ============================================================
//  UPGRADES
// ============================================================
export const UPGRADES = [
  {
    id: 'betterInk',
    icon: '🖋️',
    name: 'Luminous Ink',
    description: 'Warm-glowing dots appear on map cells that are close to a correct position.',
    cost: 40,
  },
  {
    id: 'enchantedLens',
    icon: '🔭',
    name: 'Enchanted Lens',
    description: 'After scoring, the exact correct positions are highlighted on the map.',
    cost: 60,
  },
  {
    id: 'cozyCurtains',
    icon: '🪟',
    name: 'Cozy Curtains',
    description: 'A calmer atmosphere. Reputation loss from poor maps is halved.',
    cost: 30,
  },
  {
    id: 'thickParchment',
    icon: '📜',
    name: 'Thick Parchment',
    description: 'Premium paper commands a premium price — all map sales earn 25% more gold.',
    cost: 50,
  },
  {
    id: 'crystalBall',
    icon: '🔮',
    name: 'Crystal Ball',
    description: 'Once per night, reveal one mystery clue as a pre-placed tile on the map.',
    cost: 80,
  },
];
